version: '3.5'

services:

  springcloudconfig-lab:
    image: hyness/spring-cloud-config-server:3.0.4-jdk15
    container_name: springcloudconfig-lab
    restart: unless-stopped
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=git@github.com:diegopm2000-lab/lab-config-dev.git
    ports:
      - 8889:8888
    volumes:
      - ./springcfg_ssh_config/id_rsa:/root/.ssh/id_rsa:ro
      - ./springcfg_ssh_config/known_hosts:/root/.ssh/known_hosts:ro
