version: '3.5'

services:

  postgresql:
    image: postgres:12.4
    ports:
      - 0.0.0.0:5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - sample-postgresql:/var/lib/postgresql/data

volumes:
  sample-postgresql:
